    var villagers={};
    Array.prototype.slice.call(document.querySelectorAll("table.roundy:nth-child(5) tr")).forEach((tr) => {
        var name=tr.querySelector("td:nth-child(1)");
        var v={};
        if(!name)return;
        v.name=name.innerText;
        var personality=tr.querySelector("td:nth-child(3)");
        if(!personality)return;
        v.personality=personality.innerText;
        var species=tr.querySelector("td:nth-child(4)");
        if(!species)return;
        v.species=species.innerText;
        var birthday=tr.querySelector("td:nth-child(5)");
        if(!birthday)return;
        v.birthday=birthday.innerText;
        var catchphrase=tr.querySelector("td:nth-child(6)");
        if(!catchphrase)return;
        v.catchphrase=catchphrase.innerText;
        var hobbies=tr.querySelector("td:nth-child(7)");
        if(!hobbies)return;
        v.hobbies=hobbies.innerText;
        villagers[v.name]=v;
    });
    console.log(JSON.stringify(villagers));