package main

type villagerName uint16

type villagersName struct {
	Name *villagerName
}

const (
	villagerNameAdmiral villagerName = iota
	villagerNameAgentS
	villagerNameAgnes
	villagerNameAl
	villagerNameAlfonso
	villagerNameAlice
	villagerNameAlli
	villagerNameAmelia
	villagerNameAnabelle
	villagerNameAnchovy
	villagerNameAngus
	villagerNameAnicotti
	villagerNameAnkha
	villagerNameAnnalisa
	villagerNameAnnalise
	villagerNameAntonio
	villagerNameApollo
	villagerNameApple
	villagerNameAstrid
	villagerNameAudie
	villagerNameAurora
	villagerNameAva
	villagerNameAvery
	villagerNameAxel
	villagerNameBaabara
	villagerNameBam
	villagerNameBangle
	villagerNameBarold
	villagerNameBea
	villagerNameBeardo
	villagerNameBeau
	villagerNameBecky
	villagerNameBella
	villagerNameBenedict
	villagerNameBenjamin
	villagerNameBertha
	villagerNameBettina
	villagerNameBianca
	villagerNameBiff
	villagerNameBigTop
	villagerNameBill
	villagerNameBilly
	villagerNameBiskit
	villagerNameBitty
	villagerNameBlaire
	villagerNameBlanche
	villagerNameBlathers
	villagerNameBluebear
	villagerNameBob
	villagerNameBonbon
	villagerNameBones
	villagerNameBoomer
	villagerNameBoone
	villagerNameBoots
	villagerNameBoris
	villagerNameBoyd
	villagerNameBree
	villagerNameBroccolo
	villagerNameBroffina
	villagerNameBruce
	villagerNameBubbles
	villagerNameBuck
	villagerNameBud
	villagerNameBunnie
	villagerNameButch
	villagerNameBuzz
	villagerNameCJ
	villagerNameCally
	villagerNameCamofrog
	villagerNameCanberra
	villagerNameCandi
	villagerNameCarmen
	villagerNameCaroline
	villagerNameCarrie
	villagerNameCashmere
	villagerNameCeleste
	villagerNameCelia
	villagerNameCesar
	villagerNameChadder
	villagerNameCharlise
	villagerNameCheri
	villagerNameCherry
	villagerNameChester
	villagerNameChevre
	villagerNameChief
	villagerNameChops
	villagerNameChow
	villagerNameChrissy
	villagerNameClaude
	villagerNameClaudia
	villagerNameClay
	villagerNameCleo
	villagerNameClyde
	villagerNameCoach
	villagerNameCobb
	villagerNameCoco
	villagerNameCole
	villagerNameColton
	villagerNameCookie
	villagerNameCousteau
	villagerNameCrackle
	villagerNameCranston
	villagerNameCroque
	villagerNameCube
	villagerNameCurlos
	villagerNameCurly
	villagerNameCurt
	villagerNameCyd
	villagerNameCyrano
	villagerNameCyrus
	villagerNameDaisy
	villagerNameDaisyMae
	villagerNameDeena
	villagerNameDeirdre
	villagerNameDel
	villagerNameDeli
	villagerNameDerwin
	villagerNameDiana
	villagerNameDiva
	villagerNameDizzy
	villagerNameDobie
	villagerNameDoc
	villagerNameDom
	villagerNameDora
	villagerNameDotty
	villagerNameDrago
	villagerNameDrake
	villagerNameDrift
	villagerNameEd
	villagerNameEgbert
	villagerNameElise
	villagerNameEllie
	villagerNameElmer
	villagerNameEloise
	villagerNameElvis
	villagerNameErik
	villagerNameEugene
	villagerNameEunice
	villagerNameFang
	villagerNameFauna
	villagerNameFelicity
	villagerNameFilbert
	villagerNameFlick
	villagerNameFlip
	villagerNameFlo
	villagerNameFlora
	villagerNameFlurry
	villagerNameFrancine
	villagerNameFrank
	villagerNameFreckles
	villagerNameFreya
	villagerNameFriga
	villagerNameFrita
	villagerNameFrobert
	villagerNameFuchsia
	villagerNameGabi
	villagerNameGala
	villagerNameGaston
	villagerNameGayle
	villagerNameGenji
	villagerNameGigi
	villagerNameGladys
	villagerNameGloria
	villagerNameGoldie
	villagerNameGonzo
	villagerNameGoose
	villagerNameGraham
	villagerNameGreta
	villagerNameGrizzly
	villagerNameGroucho
	villagerNameGruff
	villagerNameGullivarrr
	villagerNameGulliver
	villagerNameGwen
	villagerNameHamlet
	villagerNameHamphrey
	villagerNameHans
	villagerNameHarry
	villagerNameHarvey
	villagerNameHazel
	villagerNameHenry
	villagerNameHippeux
	villagerNameHopkins
	villagerNameHopper
	villagerNameHornsby
	villagerNameHuck
	villagerNameHugh
	villagerNameIggly
	villagerNameIke
	villagerNameIsabelle
	villagerNameJacob
	villagerNameJacques
	villagerNameJakey
	villagerNameJambette
	villagerNameJay
	villagerNameJeremiah
	villagerNameJitters
	villagerNameJoey
	villagerNameJudy
	villagerNameJulia
	villagerNameJulian
	villagerNameJune
	villagerNameKkSlider
	villagerNameKabuki
	villagerNameKatt
	villagerNameKeaton
	villagerNameKen
	villagerNameKetchup
	villagerNameKevin
	villagerNameKicks
	villagerNameKidCat
	villagerNameKidd
	villagerNameKiki
	villagerNameKitt
	villagerNameKitty
	villagerNameKlaus
	villagerNameKnox
	villagerNameKody
	villagerNameKyle
	villagerNameLabel
	villagerNameLabelle
	villagerNameLeif
	villagerNameLeonardo
	villagerNameLeopold
	villagerNameLily
	villagerNameLimberg
	villagerNameLionel
	villagerNameLloid
	villagerNameLobo
	villagerNameLolly
	villagerNameLopez
	villagerNameLouie
	villagerNameLucha
	villagerNameLucky
	villagerNameLucy
	villagerNameLyman
	villagerNameMabel
	villagerNameMac
	villagerNameMaddie
	villagerNameMaelle
	villagerNameMaggie
	villagerNameMallary
	villagerNameMaple
	villagerNameMarcel
	villagerNameMarcie
	villagerNameMargie
	villagerNameMarina
	villagerNameMarshal
	villagerNameMathilda
	villagerNameMegan
	villagerNameMelba
	villagerNameMerengue
	villagerNameMerry
	villagerNameMidge
	villagerNameMint
	villagerNameMira
	villagerNameMiranda
	villagerNameMitzi
	villagerNameMoe
	villagerNameMolly
	villagerNameMonique
	villagerNameMonty
	villagerNameMoose
	villagerNameMott
	villagerNameMuffy
	villagerNameMurphy
	villagerNameNan
	villagerNameNana
	villagerNameNaomi
	villagerNameNate
	villagerNameNibbles
	villagerNameNorma
	villagerNameOHare
	villagerNameOctavian
	villagerNameOlaf
	villagerNameOlive
	villagerNameOlivia
	villagerNameOpal
	villagerNameOrville
	villagerNameOzzie
	villagerNamePancetti
	villagerNamePango
	villagerNamePaolo
	villagerNamePapi
	villagerNamePascal
	villagerNamePashmina
	villagerNamePate
	villagerNamePatty
	villagerNamePaula
	villagerNamePeaches
	villagerNamePeanut
	villagerNamePecan
	villagerNamePeck
	villagerNamePeewee
	villagerNamePeggy
	villagerNamePekoe
	villagerNamePenelope
	villagerNamePhil
	villagerNamePhoebe
	villagerNamePierce
	villagerNamePietro
	villagerNamePinky
	villagerNamePiper
	villagerNamePippy
	villagerNamePlucky
	villagerNamePompom
	villagerNamePoncho
	villagerNamePoppy
	villagerNamePortia
	villagerNamePrince
	villagerNamePuck
	villagerNamePuddles
	villagerNamePudge
	villagerNamePunchy
	villagerNamePurrl
	villagerNameQueenie
	villagerNameQuillson
	villagerNameRaddle
	villagerNameRasher
	villagerNameRaymond
	villagerNameRedd
	villagerNameReese
	villagerNameReneigh
	villagerNameRenee
	villagerNameResetti
	villagerNameRex
	villagerNameRhonda
	villagerNameRibbot
	villagerNameRicky
	villagerNameRizzo
	villagerNameRoald
	villagerNameRobin
	villagerNameRocco
	villagerNameRocket
	villagerNameRod
	villagerNameRodeo
	villagerNameRodney
	villagerNameRolf
	villagerNameRooney
	villagerNameRory
	villagerNameRoscoe
	villagerNameRosie
	villagerNameRover
	villagerNameRowan
	villagerNameRuby
	villagerNameRudy
	villagerNameSable
	villagerNameSaharah
	villagerNameSally
	villagerNameSamson
	villagerNameSandy
	villagerNameSavannah
	villagerNameScoot
	villagerNameShari
	villagerNameSheldon
	villagerNameShep
	villagerNameSherb
	villagerNameSimon
	villagerNameSkye
	villagerNameSly
	villagerNameSnake
	villagerNameSoleil
	villagerNameSparro
	villagerNameSpike
	villagerNameSpork
	villagerNameSprinkle
	villagerNameSprocket
	villagerNameStatic
	villagerNameStella
	villagerNameSterling
	villagerNameStinky
	villagerNameStitches
	villagerNameStu
	villagerNameSydney
	villagerNameSylvana
	villagerNameSylvia
	villagerNameTBone
	villagerNameTabby
	villagerNameTad
	villagerNameTammi
	villagerNameTammy
	villagerNameTangy
	villagerNameTank
	villagerNameTasha
	villagerNameTeddy
	villagerNameTex
	villagerNameTia
	villagerNameTiffany
	villagerNameTimbra
	villagerNameTimmy
	villagerNameTipper
	villagerNameTom
	villagerNameTomNook
	villagerNameTommy
	villagerNameTruffles
	villagerNameTucker
	villagerNameTutu
	villagerNameTwiggy
	villagerNameTybalt
	villagerNameUrsala
	villagerNameVelma
	villagerNameVesta
	villagerNameVic
	villagerNameVictoria
	villagerNameViolet
	villagerNameVivian
	villagerNameVladimir
	villagerNameWade
	villagerNameWalker
	villagerNameWalt
	villagerNameWartJr
	villagerNameWeber
	villagerNameWendy
	villagerNameWhitney
	villagerNameWilbur
	villagerNameWillow
	villagerNameWinnie
	villagerNameWisp
	villagerNameWolfgang
	villagerNameYuka
	villagerNameZell
	villagerNameZipperTBunny
	villagerNameZucker
)
