package main

type villagerAspiration uint8

type villagersAspiration struct {
	Aspiration villagerAspiration
}

const (
	villagerAspirationActor villagerAspiration = iota
	villagerAspirationAesthetician
	villagerAspirationArchaeologist
	villagerAspirationArchitect
	villagerAspirationArtist
	villagerAspirationAstronaut
	villagerAspirationBaseballPlayer
	villagerAspirationBasketballPlayer
	villagerAspirationBoxer
	villagerAspirationCeo
	villagerAspirationCarpenter
	villagerAspirationCartoonist
	villagerAspirationChef
	villagerAspirationDancer
	villagerAspirationDentist
	villagerAspirationDermatologist
	villagerAspirationDesigner
	villagerAspirationDetective
	villagerAspirationDoctor
	villagerAspirationDrummer
	villagerAspirationEsthetician
	villagerAspirationExplorer
	villagerAspirationFashionDesigner
	villagerAspirationFigureSkater
	villagerAspirationFirefighter
	villagerAspirationFisherman
	villagerAspirationFlorist
	villagerAspirationForestRanger
	villagerAspirationGuitarist
	villagerAspirationGymnast
	villagerAspirationHairStylist
	villagerAspirationIllustrator
	villagerAspirationJournalist
	villagerAspirationJudge
	villagerAspirationLawyer
	villagerAspirationMakeupArtist
	villagerAspirationMarathonRunner
	villagerAspirationMayor
	villagerAspirationModel
	villagerAspirationMovieDirector
	villagerAspirationMovieStar
	villagerAspirationMusician
	villagerAspirationPainter
	villagerAspirationPastryChef
	villagerAspirationPharmacist
	villagerAspirationPhotographer
	villagerAspirationPianist
	villagerAspirationPilot
	villagerAspirationPoet
	villagerAspirationPoliceOfficer
	villagerAspirationPolitician
	villagerAspirationPresident
	villagerAspirationProGolfer
	villagerAspirationProWrestler
	villagerAspirationProfessor
	villagerAspirationProgrammer
	villagerAspirationRaceCarDriver
	villagerAspirationRugbyPlayer
	villagerAspirationSinger
	villagerAspirationSoccerPlayer
	villagerAspirationStylist
	villagerAspirationSumoWrestler
	villagerAspirationSuperhero
	villagerAspirationSwimmer
	villagerAspirationTeacher
	villagerAspirationTennisPlayer
	villagerAspirationTourGuide
	villagerAspirationTranslator
	villagerAspirationTycoon
	villagerAspirationViolinist
	villagerAspirationVolleyballPlayer
	villagerAspirationWriter
)
